WebovaAplikace/Models/ErrorViewModel.cs
namespace WebovaAplikace.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebovaAplikace/Models/Kuryr.cs
namespace WebovaAplikace.Models
{
    public class Kuryr
    {
        public string jmeno { get; set; }
        public int trzba { get; set; }
        public int dyska { get; set; }  
        public int penezenka { get; set; }
        public int tankovani { get; set; }
        public int nakupovani { get; set; }

        public int celkem;

    }
}

WebovaAplikace/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WebovaAplikace.Models;

namespace WebovaAplikace.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        

        

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebovaAplikace/Controllers/OtazkaController.cs
using Microsoft.AspNetCore.Mvc;
using WebovaAplikace.Models;


namespace WebovaAplikace.Controllers
{
    public class OtazkaController : Controller
    {
        public IActionResult Index(Kuryr kuryr)
        {
            kuryr.celkem = (kuryr.penezenka + kuryr.dyska - kuryr.tankovani - kuryr.nakupovani - kuryr.trzba); 
            Kuryr kuryr2 = new Kuryr();
            return View();
        }

        public IActionResult Input()
        {
            var kuryr1 = new Kuryr();
            return View(kuryr1);
        }

        public IActionResult VytvoritKuryra(Kuryr kuryr)
        {
            kuryr.celkem = (kuryr.penezenka + kuryr.dyska - kuryr.tankovani - kuryr.nakupovani - kuryr.trzba);

            return View("Index");

        }
    }
}

WebovaAplikace/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebovaAplikace/Views/Otazka/Index.cshtml
@model WebovaAplikace.Models.Kuryr


@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<h1> Vysledek kalkulace </h1>
<p> V penezence kuryrovi zustane @Kuryr.celkem  </p>

WebovaAplikace/Views/Otazka/Input.cshtml
<h3>Na této stránce zadáte vaše hodnoty </h3>
<hr />
@model Kuryr


<div class="row">

	<div class="col-6">

		<div class="card">



			<div class="card-header">
				<h5>Zadejte hodnoty</h5>
			</div>

			<div class="card-body">
				<form asp-controller="Otazka" asp-action="V" method="post">
					<div class="mb-3">
						<label class="form-label">Jmeno</label>
						<input asp-for="jmeno" type="text" class="form-control" />
					</div>

					<div class="mb-3">
						<label class="form-label">Trzba</label>
						<input asp-for="trzba" type="number" class="form-control" />
					</div>

					<div class="mb-3">
						<label class="form-label">Dyska</label>
						<input asp-for="dyska" type="number" class="form-control" />
					</div>

					<div class="mb-3">
						<label class="form-label">Penezenka</label>
						<input asp-for="penezenka" type="number" class="form-control" />
					</div>

					<div class="mb-3">
						<label class="form-label">Tankovani</label>
						<input asp-for="tankovani" type="number" class="form-control" />
					</div>

					<div class="mb-3">
						<label class="form-label">Nakupovani</label>
						<input asp-for="nakupovani" type="number" class="form-control" />
					</div>

					<div class="mb-3">
						<button type="submit" class="btn btn-primary">Odeslat</button>
					</div>

				</form>
			</div>

			<div class="card-footer"></div>
		</div>






	</div>

</div>

WebovaAplikace/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebovaAplikace</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebovaAplikace.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Otazka" asp-action="Index">WebovaAplikace</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Otazka" asp-action="Index">Otazka</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Otazka" asp-action="Input">Input</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebovaAplikace - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>